version: '2.1'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.0.1
    container_name: FILEBEAT
    user: root
    volumes:
      - /home/linux/logtrail4ags/filebeat-linux.yml:/usr/share/filebeat/filebeat.yml
    volumes_from:
      - container:PORTALWA
      - container:SERVER
